config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users

  root to: 'projects#index'

  resources :projects do
    resources :tasks do
      patch :done, on: :member
    end
  end

  namespace :api do
    resource :tinymce_images, only: :create
  end

  resources :precedences

  match '*a', to: 'errors#not_found', via: :all

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/task.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: tasks
#
#  id            :bigint           not null, primary key
#  deadline      :date
#  description   :text
#  title         :text             not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  precedence_id :bigint           default(2)
#  project_id    :bigint
#  status_id     :bigint           default(1)
#
# Indexes
#
#  index_tasks_on_precedence_id  (precedence_id)
#  index_tasks_on_project_id     (project_id)
#  index_tasks_on_status_id      (status_id)
#
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :precedence
  belongs_to :status

  has_many :tinymce_images, dependent: :destroy

  validates :title, presence: true
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true
class TasksController < ApplicationController
  before_action :task, only: %i[show edit update destroy done]
  before_action :project, only: %i[edit done]

  def create
    task
    task.assign_attributes(task_params)

    respond_to do |format|
      if task.save
        flash[:success] = t('activerecord.models.task.create.flash.success')
        format.html { redirect_to projects_path }
        format.json { render :index, status: :created, location: @task }
      else
        flash[:danger] = t('activerecord.models.task.create.flash.danger')
        format.html { redirect_to projects_path }
        format.json { render json: task.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    task
  end

  def update
    respond_to do |format|
      if task.update(task_params)
        flash[:success] = t('activerecord.models.task.update.flash.success')
        format.html { redirect_to projects_path }
        format.json { render :index, status: :ok, location: task }
      else
        flash[:danger] = t('activerecord.models.task.update.flash.danger')
        format.html { render :edit }
        format.json { render json: task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if task.destroy
        flash[:success] = t('activerecord.models.task.destroy.flash.success')
        format.html { redirect_to projects_path }
        format.json { head :no_content }
      else
        flash[:danger] = task.errors.full_messages
        format.html { redirect_to projects_path }
      end
    end
  end

  def done
    if task.update(status_id: params[:task][:status])
      redirect_to(projects_path, notice: t('activerecord.models.task.done.flash.success_1')) if params[:task][:status] == '4'
      redirect_to(projects_path, notice: t('activerecord.models.task.done.flash.success_2')) if params[:task][:status] == '2'
    else
      render(projects_path, danger: [t('activerecord.models.task.done.flash.danger'), task.errors.full_messages.join(',')].join)
    end
  end

  private

  def task
    @task ||= params[:id].present? ? tasks.find(params[:id]) : tasks.new
  end

  def tasks
    @tasks ||= project.tasks
  end

  def project
    @project ||= begin
                   Project.find(params[:project_id])
                 rescue StandardError
                   nil
                 end
  end

  def task_params
    params.require(:task).permit(:project_id, :title, :description, :deadline, :precedence_id, :status_id, :tinymce_image)
  end
end

app/views/tasks/_form.html.slim
= f.error_notification
= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
.form-inputs
  = f.association :project,
      as: :select,
      label: t('activerecord.models.project.one'),
      label_method:  :title,
      include_blank: false

  = f.input :title,
      label: t('activerecord.models.task.one'),
      placeholder: t('activerecord.models.task.attributes.title.placeholder')

  = f.association :precedence,
      as: :select,
      label: t('activerecord.models.precedence.one'),
      include_blank: false

  = f.association :status,
      as: :select,
      label: t('activerecord.models.status.one'),
      label_method:  :title,
      include_blank: false

  = f.input :deadline, as: :date,
      label: t('activerecord.models.deadline.one'),
      placeholder: t('activerecord.models.task.attributes.deadline.placeholder')

  = f.input :description,
      input_html: {class: 'tinymce', rows: 10, cols: 60},
      label: t('activerecord.models.description.one'),
      placeholder: t('activerecord.models.task.attributes.description.placeholder')

  = tinymce(uploadimage_form_url: api_tinymce_images_path)

app/views/tasks/edit.html.slim
= simple_form_for([@project, @task],html: { class: 'col-sm-12' }) do |f|
  .container.bg-faded
    p.pt-4
    .card.border-muted.shadow.col-lg-6.color-task
      .card-header.bg-transparent.border-muted
        h4
          = t('activerecord.models.task.edit')
      .card-body.text-primary
        = render partial: "form", locals: { f: f }
      .card-footer.bg-transparent.border-muted
        .row
          .col-2
            = link_to t('cancel'), projects_path, class: 'btn btn-danger'
          .col-10.text-right
            p =  f.submit t('save')