config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users

  root to: 'projects#index'

  resources :projects do
    resources :tasks do
      patch :done, on: :member
    end
  end

  namespace :api do
    resource :tinymce_images, only: :create
  end

  resources :precedences

  match '*a', to: 'errors#not_found', via: :all

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/precedence.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: precedences
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Precedence < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates :title, presence: true
end

app/controllers/precedences_controller.rb
# frozen_string_literal: true
class PrecedencesController < ApplicationController
  before_action :precedence, only: %i[show edit update destroy]

  def index
    @precedences = Precedence.all
  end

  def new
    @precedence = Precedence.new
  end

  def create
    @precedence = Precedence.new(precedence_params)

    respond_to do |format|
      if @precedence.save
        flash[:success] = t('activerecord.models.precedence.create.flash.success')
        format.html { redirect_to precedences_path }
        format.json { render :index, status: :created, location: @precedence }
      else
        flash[:danger] = t('activerecord.models.precedence.create.flash.danger')
        format.html { render :new }
        format.json { render json: @precedence.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @precedence.update(precedence_params)
        flash[:success] = t('activerecord.models.precedence.update.flash.success')
        format.html { redirect_to precedences_path }
        format.json { render :index, status: :ok, location: @precedence }
      else
        flash[:danger] = t('activerecord.models.precedence.update.flash.danger')
        format.html { render :edit }
        format.json { render json: @precedence.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @precedence.destroy
    respond_to do |format|
      flash[:success] = t('activerecord.models.precedence.destroy.flash.success')
      format.html { redirect_to precedences_path }
      format.json { head :no_content }
    end
  end

  private

  def precedence
    @precedence ||= begin
                      Precedence.find(params[:id])
                    rescue StandardError
                      nil
                    end
    render_404 unless @precedence
  end

  def precedence_params
    params.require(:precedence).permit(:title)
  end
end

app/views/precedences/_form.html.slim
= f.error_notification
= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
.form-inputs
  = f.input :title,
      placeholder: t('activerecord.models.precedence.attributes.title.placeholder'),
      required: true,
      label: t('precedence_name')

app/views/precedences/edit.html.slim
= simple_form_for(@precedence, html: { class: 'col-sm-12' }) do |f|
  .container.bg-faded
    p.pt-4
    .card.border-muted.shadow.col-lg-6.color-precedences
      .card-header.bg-transparent.border-muted
        h4 = t('activerecord.models.precedence.edit')
      .card-body.text-primary
        = render partial: "form", locals: { f: f }
      .card-footer.bg-transparent.border-muted
        .row
          .col-2
            = link_to t('cancel'), precedences_path, class: 'btn btn-danger'
          .col-10.text-right
            p = f.submit t('save')

app/views/precedences/index.html.slim
.container.color-task
  p.pt-4
  .card.border-muted.lg-12.color-precedences
    h2.text-center
      = t('activerecord.models.precedence.one')
  .container.bg-faded
    - @precedences.each do |precedence|
      p.pt-2
      .card.border-muted.lg-12.color-project
        .card-body.text-primary
          .row
            .col-1
              i.handle.fas.fa-tools.fa-2x
            .col-9
              a.card-link.text-white href="#"
                h2
                  = precedence.title
            .col-2.text-right
              span
                = link_to raw('<i class="fas fa-pencil-alt fa-2x"></i>'), edit_precedence_path(precedence),
                    class: 'btn btn-p text-primary',
                    title: t('edit')
                i.pl-1.pr-1
                | |
                i.pl-1.pr-1
                = link_to raw('<i class="fas fa-trash-alt fa-2x"></i>'), precedence_path(precedence),
                    class: 'btn btn-p text-primary',
                    method: :delete, data: {confirm: t('confirm')},
                    title: t('delete')
    .container
      p.pt-4
      .btn-toolbar.justify-content-between role="toolbar"
        = link_to raw('<i class="fas fa-home"></i> Home'), root_path, class: 'btn btn-warning'
        = link_to raw('<i class="i fa fa-plus fa-lg"></i> Add'), new_precedence_path, class: 'btn btn-primary btn-right'
      p.pt-4

app/views/precedences/new.html.slim
= simple_form_for(@precedence, html: { class: 'col-sm-12' }) do |f|
  .container.bg-faded
    p.pt-4
    .card.border-muted.shadow.col-lg-6.color-precedences
      .card-header.bg-transparent.border-muted
        h4 = t('activerecord.models.precedence.create_new')
      .card-body.text-primary
        = render partial: "form", locals: { f: f }
      .card-footer.bg-transparent.border-muted
        .row
          .col-2
            = link_to t('cancel'), precedences_path, class: 'btn btn-danger'
          .col-10 style='text-align: right'
            p = f.submit t('create')