config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users

  root to: 'projects#index'

  resources :projects do
    resources :tasks do
      patch :done, on: :member
    end
  end

  namespace :api do
    resource :tinymce_images, only: :create
  end

  resources :precedences

  match '*a', to: 'errors#not_found', via: :all

  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/project.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: projects
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_projects_on_user_id  (user_id)
#
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, presence: true
end

app/controllers/projects_controller.rb
# frozen_string_literal: true
class ProjectsController < ApplicationController
  before_action :project, only: %i[show edit update destroy]

  def index
    @search = Project.all.where(user_id: authenticate_user!).ransack(params[:search])
    @search.sorts = ['name asc', 'created_at desc'] if @search.sorts.empty?
    @projects = @search.result.includes(:user, @tasks).paginate(page: params[:page], per_page: 3)
    @task = Task.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        flash[:success] = t('activerecord.models.project.create.flash.success')
        format.html { redirect_to projects_path }
        format.json { render :index, status: :created, location: @project }
      else
        flash[:danger] = t('activerecord.models.project.create.flash.danger')
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        flash[:success] = t('activerecord.models.project.update.flash.success')
        format.html { redirect_to projects_path }
        format.json { render :index, status: :ok, location: @project }
      else
        flash[:danger] = t('activerecord.models.project.update.flash.danger')
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      flash[:success] = t('activerecord.models.project.destroy.flash.success')
      format.html { redirect_to projects_path }
      format.json { head :no_content }
    end
  end

  private

  def project
    @project ||= begin
                   Project.find(params[:id])
                 rescue StandardError
                   nil
                 end
    render_404 unless @project
  end

  def project_params
    params.require(:project).permit(:title, :user_id)
  end
end

app/views/projects/_auth_user.html.slim
button.btn.btn-p.text-primary data-target="#AuthUser" data-toggle="modal" type="button"
  i.fas.fa-user.fa-2x aria-hidden="true"
/! Modal
#AuthUser.modal.fade aria-hidden="true" aria-labelledby="AuthUserLabel" role="dialog" tabindex="-1"
  .modal-dialog.modal-dialog-centered.modal-lg role="document"
    .modal-content.color-auth
      .modal-header
        .container.auth_title
          h2
            = current_user.login if user_signed_in?
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  ×
      .modal-body#AuthUserLabel
        .container.auth_body
          = link_to  raw('<i class="fas fa-user-times fa-7x"></i>'), destroy_user_session_path,
                class: 'btn btn-p text-primary',
                method: :delete,
                title: t("devise.sessions.destroy.log_out")
      .modal-footer
        .container.auth_footer
          h5
            = t('devise.registrations.auth')

app/views/projects/_checked.html.erb
<script>
  $("#defaultUnchecked<%= task.id %>").click(function(e, parameters) {

    let nonUI = false;
    try {
      nonUI = parameters.nonUI;
    } catch (e) {}
    let checked = nonUI ? !this.checked : this.checked;
    $("#edit_task_<%= task.id %>").submit();
  });
</script>

app/views/projects/_filter.html.slim
.box.box-danger
  .box-header.with-border
    h5 = t('search')
  .box-body
    .row
      .col-xs-3
        = search_form_for @search, builder: SimpleForm::FormBuilder do |f|
          = f.input :title_cont,
              class: 'form-control',
              required: false,
              label: false,
              placeholder: t('activerecord.models.project.attributes.search.placeholder')
          = f.input :tasks_title_cont,
              class: 'form-control',
              required: false,
              label: false,
              placeholder: t('activerecord.models.task.attributes.search.title.placeholder')
          = f.input :tasks_description_cont,
              class: 'form-control',
              required: false,
              label: false,
              placeholder: t('activerecord.models.task.attributes.search.description.placeholder')
          .btn-toolbar.justify-content-between role="toolbar"
            = f.submit t('search'), class: 'btn btn-primary'
            = link_to I18n.t('clear'), request.path, class: 'btn btn-warning btn-right'

app/views/projects/_footer.html.slim
.card-footer.bg-transparent.border-muted.text-center.footer-padding
  | My test simple ToDoList

app/views/projects/_form.html.slim
= f.error_notification
= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
.form-inputs
  = f.input :title,
      placeholder: t('activerecord.models.project.attributes.title.placeholder'),
      required: true,
      label: t('project_name')

  = f.association :user,
      as: :select,
      label_method: :login,
      label: t('activerecord.models.user.one'),
      include_blank: false

app/views/projects/_header.html.slim
.container
  nav.navbar.color-navbar.mixin-flex-bar
    nav.navbar.navbar-dark
      = link_to '#search_form', role: 'button', data: {toggle: 'collapse'}, aria: {expanded: false, controls: 'search_form'} do
        i.fas.fa-search.fa-2x
    .collapse#search_form
      = render 'filter'
    nav.navbar.navbar-dark
      = link_to raw('<i class="fas fa-tools fa-2x"></i>'), precedences_path,
          class: 'btn btn-p text-primary',
          title: t('config')
    nav.navbar.navbar-dark
      ul.navbar-nav.ml-auto
        li.nav-item
          a.nav-link.waves-effect.waves-light
            i.fab.fa-facebook-f
        li.nav-item
          a.nav-link.waves-effect.waves-light
            i.fab.fa-instagram
    nav.navbar
      h2.text-center
        a href="/" style="text-decoration: none"
          | SIMPLE ToDo LISTS
          h5.text-white
            = current_user.login if user_signed_in?
    nav.navbar.navbar-dark
      ul.navbar-nav.ml-auto
        li.nav-item
          a.nav-link.waves-effect.waves-light
            i.fab.fa-twitter
        li.nav-item
          a.nav-link.waves-effect.waves-light
            i.fab.fa-google-plus-g
    nav.navbar.navbar-dark
      button.navbar-toggler data-target="#lang" data-toggle="collapse" type="button"
        i.fas.fa-language.fa-2x
      #lang.collapse.navbar-collapse
        ul.navbar-nav.ml-auto
          li.nav-item
            a.nav-link class=("nav-item#{" active" if I18n.locale == :uk}")
              = link_to 'Укр', {locale: :uk}, class: 'btn btn-sm btn-outline-primary btn-block'
          li.nav-item
            a.nav-link class=("nav-item#{" active" if I18n.locale == :en}")
              = link_to 'En', {locale: :en}, class: 'btn btn-sm btn-outline-primary btn-block'
    nav.navbar
      span#inputGroup-sizing-lg
        = render 'auth_user'

app/views/projects/_index_task.html.slim
.row
  .col-12
    .input-group.input-group-lg
      .input-group-prepend
        span.input-group-text
          .custom-control.custom-checkbox
            = check_box_tag "defaultUnchecked#{task.id}", '',
                task.status.id == 4 ? true : false,
                class: 'custom-control-input'
            = label_tag "defaultUnchecked#{task.id}", '', class: 'custom-control-label'
      = text_field_tag :title, task.title,
          readonly: "true",
          class: "form-control",
          style: task.status.id == 4 ? "text-decoration: line-through" : ""
      .input-group-prepend
        span#inputGroup-sizing-lg.input-group-text.text-primary
          = render partial: 'show_task_info', locals: {project: project, task: task}
          i.pl-1.pr-1
          = link_to raw('<i class="fas fa-pen-square fa-sm"></i>'), edit_project_task_path(project, task),
                class: 'btn.btn-p.text-primary',
                title: t('edit')
          i.pl-1.pr-1
          = link_to raw('<i class="fas fa-trash fa-sm"></i>'), project_task_path(project, task),
                class: 'btn.btn-p.text-primary',
                method: :delete,
                data: {confirm: t('confirm')},
                title: t('delete')
= render partial: 'checked', locals: {project: project, task: task}
= form_for task, url: done_project_task_path(project, task) do |f|
  = f.hidden_field :status, value: task.status.id == 4 ? 2 : 4

app/views/projects/_new_task.html.slim
= simple_form_for([project, @task]) do |f|
  .row
    .col-12
      .input-group.input-group-lg
        = f.text_field :title, as: :string, class: "form-control", placeholder: t('activerecord.models.task.create_new')
        = f.hidden_field :project_id, value: project.id
        .input-group-prepend
          span.input-group-text
            .text-primary.i.fa.fa-plus
              = f.submit ''

app/views/projects/_show_task_info.html.slim
button.btn.btn-p.text-primary data-target="#ShowTaskInfo#{task.id}" data-toggle="modal" type="button" title=t('info')
  i.far.fa-list-alt.fa-lg aria-hidden="true"
/! Modal
.modal.fade id="ShowTaskInfo#{task.id}" aria-hidden="true" aria-labelledby="ModalLabel#{task.id}" role="dialog" tabindex="-1"
  .modal-dialog.modal-dialog-centered.modal-lg role="document"
    .modal-content.color-layouts
      .modal-header
        h5.modal-title
          .row
            .col-1
              i.fas.fa-clipboard-list.fa-2x
            .col-9
              a.card-link.text-white href="#"
                h2
                  = project.title
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  ×
      .modal-header
        h6.modal-title.text-muted id="ModalLabel#{task.id}"
          .container
            .col-6
              = t("activerecord.models.status.one")+ ":" + " " +task.status.title.to_s
            .col-6
              = t("activerecord.models.precedence.one")+ ":" + " " +task.precedence.title.to_s
            .col-6
              = t("activerecord.models.task.attributes.deadline.placeholder")+ ":" + " " +task.deadline.to_s
      .modal-body.text-muted.text-left
        .task_title_info
          = task.title
        .task_description_info
          = task.description.to_s.html_safe
      .modal-footer
        h6.modal-title.text-muted
          button.btn.btn-primary data-dismiss="modal" type="button"  Close

app/views/projects/edit.html.slim
= simple_form_for(@project, html: { class: 'col-sm-12' }) do |f|
  .container.bg-faded
    p.pt-4
    .card.border-muted.shadow.col-lg-6.color-project
      .card-header.bg-transparent.border-muted
        h4 = t('activerecord.models.project.edit')
      .card-body.text-primary
        = render partial: "form", locals: { f: f }
      .card-footer.bg-transparent.border-muted
        .row
          .col-2
            = link_to t('cancel'), projects_path, class: 'btn btn-danger'
          .col-10.text-right
            p = f.submit t('save')

app/views/projects/index.html.slim
= render 'header'
.container
  .container.bg-faded
    - @projects.each do |project|
      p.pt-4
      .card.border-muted.lg-12.color-project
        .card-body.text-primary id="project_#{project.id}"
          .row
            .col-1
              i.handle.fas.fa-clipboard-list.fa-2x
            .col-9
              a.card-link.text-white href="#"
                h2
                  = project.title
            .col-2.text-right
              span
                = link_to raw('<i class="fas fa-pencil-alt fa-2x"></i>'), edit_project_path(project),
                    class: 'btn btn-p text-primary',
                    title: t('edit')
                i.pl-1.pr-1
                | |
                i.pl-1.pr-1
                = link_to raw('<i class="fas fa-trash-alt fa-2x"></i>'), project_path(project),
                    class: 'btn btn-p text-primary',
                    method: :delete, data: {confirm: t('confirm')},
                    title: t('delete')
          hr
          = render partial: 'new_task', locals: {project: project}
          - project.tasks.each do |task|
            = render partial: 'index_task', locals: {project: project, task: task}
        p.pt-4
    div.text-center.btnAddToDoList
      = link_to raw('<i class="i fa fa-plus fa-lg"></i> Add TODO List'), new_project_path, class: 'btn btn-primary'
= will_paginate @projects, list_classes: %w(pagination justify-content-center),
    previous_label: '&laquo;', next_label: '&raquo;'
= render 'footer'

app/views/projects/new.html.slim
= simple_form_for(@project, html: { class: 'col-sm-12' }) do |f|
  .container.bg-faded
    p.pt-4
    .card.border-muted.shadow.col-lg-6.color-project
      .card-header.bg-transparent.border-muted
        h4 = t('activerecord.models.project.create_new')
      .card-body.text-primary
        = render partial: "form", locals: { f: f }
      .card-footer.bg-transparent.border-muted
        .row
          .col-2
            = link_to t('cancel'), projects_path, class: 'btn btn-danger'
          .col-10 style='text-align: right'
            p = f.submit t('create')